*** Variables ***
# Dashboard Section Titles
${BLOOD_GLUCOSE_TITLE}    Blood Glucose
${BLOOD_PRESSURE_TITLE}    Blood Pressure
${WEIGHT_TITLE}    Weight
${DIET_TITLE}    Diet
${EXERCISE_TITLE}    Exercise
${STEPS_TITLE}    Steps
${CGM_TITLE}    CGM
${HBA1C_TITLE}    A1C
@{DASHBOARD_SECTIONS}    ${BLOOD_GLUCOSE_TITLE}    ${BLOOD_PRESSURE_TITLE}    ${WEIGHT_TITLE}    ${DIET_TITLE}    ${EXERCISE_TITLE}    ${STEPS_TITLE}    ${CGM_TITLE}    ${HBA1C_TITLE}

# Dashboard
${EXERCISE_DASHBOARD}    exercise
${STEPS_DASHBOARD}    steps
${GLUCOSE_DASHBOARD}    glucose
${PRESSURE_DASHBOARD}    pressure

# Diary Variables
&{GLUCOSE_DIARY}    systolic=120    diastolic=80    pulse=100    time=past    period=After Snack

# Exercise Partition
${EXERCISE_MIN_MIN}    0
${EXERCISE_MIN_MIN_RESULT}    Tap to enter
${EXERCISE_MIN_MAX}    9999
${EXERCISE_MIN_NORMAL}    300
# ${EXERCISE_MIN_EXCEED_LIMIT}    10000
# ${EXERCISE_MIN_EXCEED_LIMIT_RESULT}    1000
${EXERCISE_STEPS_MIN}    0
${EXERCISE_STEPS_MIN_RESULT}    Tap to enter
${EXERCISE_STEPS_MAX}    99999
${EXERCISE_STEPS_NORMAL}    10000
${EXERCISE_STEPS_EXCEED_LIMIT}    100000
${EXERCISE_STEPS_EXCEED_LIMIT_RESULT}    10000